export const fake_roles = [
    {
        "id": "15786",
        "checked": true,
        "eligibility": "home",
        "read": true,
        "write": true,
        "open": true,
        "name": "home",
        "sub_name": "Global",
        "type": null,
        "active": "1",
        "parent": "0",
        "show": "1",
        "create": "1",
        "children": [],
        "update": false,
        "visible": true
    },
    {
        "id": "15789",
        "checked": false,
        "eligibility": "offer",
        "read": false,
        "write": false,
        "open": true,
        "name": "offer",
        "sub_name": "Global",
        "type": null,
        "active": "1",
        "parent": "0",
        "show": "0",
        "create": "0",
        "children": [],
        "update": false,
        "visible": true
    },
    {
        "id": "15792",
        "checked": false,
        "eligibility": "planning",
        "read": false,
        "write": false,
        "open": true,
        "name": "planning",
        "sub_name": "Global",
        "type": null,
        "active": "1",
        "parent": "0",
        "show": "0",
        "create": "0",
        "children": [
            {
                "id": "15795",
                "checked": false,
                "eligibility": "resource_planning",
                "read": false,
                "write": false,
                "open": true,
                "name": "planning",
                "sub_name": "resource_planning",
                "type": null,
                "active": "1",
                "parent": "15792",
                "show": "0",
                "create": "0",
                "children": [],
                "update": false,
                "visible": true
            },
            {
                "id": "15798",
                "checked": false,
                "eligibility": "project",
                "read": false,
                "write": false,
                "open": true,
                "name": "planning",
                "sub_name": "project",
                "type": null,
                "active": "1",
                "parent": "15792",
                "show": "0",
                "create": "0",
                "children": [],
                "update": false,
                "visible": true
            }
        ],
        "update": false,
        "visible": true
    },
    {
        "id": "15801",
        "checked": true,
        "eligibility": "project",
        "read": true,
        "write": true,
        "open": true,
        "name": "project",
        "sub_name": "Global",
        "type": null,
        "active": "1",
        "parent": "0",
        "show": "1",
        "create": "1",
        "children": [
            {
                "id": "15804",
                "checked": true,
                "eligibility": "Management",
                "read": true,
                "write": false,
                "open": true,
                "name": "project",
                "sub_name": "Management",
                "type": null,
                "active": "1",
                "parent": "15801",
                "show": "1",
                "create": "0",
                "children": [
                    {
                        "id": "15807",
                        "checked": false,
                        "eligibility": "Settings",
                        "read": false,
                        "write": false,
                        "open": true,
                        "name": "project",
                        "sub_name": "Settings",
                        "type": null,
                        "active": "1",
                        "parent": "15804",
                        "show": "0",
                        "create": "0",
                        "children": [],
                        "update": false,
                        "visible": true
                    },
                    {
                        "id": "15810",
                        "checked": false,
                        "eligibility": "Organization",
                        "read": false,
                        "write": false,
                        "open": true,
                        "name": "project",
                        "sub_name": "Organization",
                        "type": null,
                        "active": "1",
                        "parent": "15804",
                        "show": "0",
                        "create": "0",
                        "children": [],
                        "update": false,
                        "visible": true
                    },
                    {
                        "id": "15813",
                        "checked": false,
                        "eligibility": "Share Projects",
                        "read": false,
                        "write": false,
                        "open": true,
                        "name": "project",
                        "sub_name": "Share Projects",
                        "type": null,
                        "active": "1",
                        "parent": "15804",
                        "show": "0",
                        "create": "0",
                        "children": [],
                        "update": false,
                        "visible": true
                    },
                    {
                        "id": "15816",
                        "checked": false,
                        "eligibility": "Payment plan",
                        "read": false,
                        "write": false,
                        "open": true,
                        "name": "project",
                        "sub_name": "Payment plan",
                        "type": null,
                        "active": "1",
                        "parent": "15804",
                        "show": "0",
                        "create": "0",
                        "children": [],
                        "update": false,
                        "visible": true
                    },
                    {
                        "id": "15819",
                        "checked": false,
                        "eligibility": "Purchases",
                        "read": false,
                        "write": false,
                        "open": true,
                        "name": "project",
                        "sub_name": "Purchases",
                        "type": null,
                        "active": "1",
                        "parent": "15804",
                        "show": "0",
                        "create": "0",
                        "children": [],
                        "update": false,
                        "visible": true
                    },
                    {
                        "id": "15822",
                        "checked": false,
                        "eligibility": "Summary",
                        "read": false,
                        "write": false,
                        "open": true,
                        "name": "project",
                        "sub_name": "Summary",
                        "type": null,
                        "active": "1",
                        "parent": "15804",
                        "show": "0",
                        "create": "0",
                        "children": [],
                        "update": false,
                        "visible": true
                    },
                    {
                        "id": "15825",
                        "checked": true,
                        "eligibility": "Work Manual",
                        "read": true,
                        "write": false,
                        "open": true,
                        "name": "project",
                        "sub_name": "Work Manual",
                        "type": null,
                        "active": "1",
                        "parent": "15804",
                        "show": "1",
                        "create": "0",
                        "children": [],
                        "update": false,
                        "visible": true
                    }
                ],
                "update": false,
                "visible": true
            },
            {
                "id": "15946",
                "checked": false,
                "eligibility": "Information",
                "read": false,
                "write": false,
                "open": true,
                "name": "project",
                "sub_name": "Information",
                "type": null,
                "active": "1",
                "parent": "15801",
                "show": "0",
                "create": "0",
                "children": [],
                "update": false,
                "visible": true
            },
            {
                "id": "15828",
                "checked": false,
                "eligibility": "Order",
                "read": false,
                "write": false,
                "open": true,
                "name": "project",
                "sub_name": "Order",
                "type": null,
                "active": "1",
                "parent": "15801",
                "show": "0",
                "create": "0",
                "children": [],
                "update": false,
                "visible": true
            },
            {
                "id": "15831",
                "checked": false,
                "eligibility": "time attest",
                "read": false,
                "write": false,
                "open": true,
                "name": "project",
                "sub_name": "time attest",
                "type": null,
                "active": "1",
                "parent": "15801",
                "show": "0",
                "create": "0",
                "children": [],
                "update": false,
                "visible": true
            },
            {
                "id": "15834",
                "checked": false,
                "eligibility": "Attachment",
                "read": false,
                "write": false,
                "open": true,
                "name": "project",
                "sub_name": "Attachment",
                "type": null,
                "active": "1",
                "parent": "15801",
                "show": "0",
                "create": "0",
                "children": [],
                "update": false,
                "visible": true
            },
            {
                "id": "15837",
                "checked": true,
                "eligibility": "Ata",
                "read": true,
                "write": true,
                "open": true,
                "name": "project",
                "sub_name": "Ata",
                "type": null,
                "active": "1",
                "parent": "15801",
                "show": "1",
                "create": "1",
                "children": [
                    {
                        "id": "15840",
                        "checked": true,
                        "eligibility": "External ata",
                        "read": true,
                        "write": true,
                        "open": true,
                        "name": "project",
                        "sub_name": "External ata",
                        "type": null,
                        "active": "1",
                        "parent": "15837",
                        "show": "1",
                        "create": "1",
                        "children": [],
                        "update": false,
                        "visible": true
                    },
                    {
                        "id": "15843",
                        "checked": true,
                        "eligibility": "Internal ata",
                        "read": true,
                        "write": true,
                        "open": true,
                        "name": "project",
                        "sub_name": "Internal ata",
                        "type": null,
                        "active": "1",
                        "parent": "15837",
                        "show": "1",
                        "create": "1",
                        "children": [],
                        "update": false,
                        "visible": true
                    },
                    {
                        "id": "15846",
                        "checked": true,
                        "eligibility": "Forecast",
                        "read": true,
                        "write": true,
                        "open": true,
                        "name": "project",
                        "sub_name": "Forecast",
                        "type": null,
                        "active": "1",
                        "parent": "15837",
                        "show": "1",
                        "create": "1",
                        "children": [],
                        "update": false,
                        "visible": true
                    }
                ],
                "update": false,
                "visible": true
            },
            {
                "id": "15849",
                "checked": false,
                "eligibility": "Deviation",
                "read": false,
                "write": false,
                "open": true,
                "name": "project",
                "sub_name": "Deviation",
                "type": null,
                "active": "1",
                "parent": "15801",
                "show": "0",
                "create": "0",
                "children": [
                    {
                        "id": "15852",
                        "checked": false,
                        "eligibility": "External deviation",
                        "read": false,
                        "write": false,
                        "open": true,
                        "name": "project",
                        "sub_name": "External deviation",
                        "type": null,
                        "active": "1",
                        "parent": "15849",
                        "show": "0",
                        "create": "0",
                        "children": [],
                        "update": false,
                        "visible": true
                    },
                    {
                        "id": "15855",
                        "checked": false,
                        "eligibility": "Internal deviation",
                        "read": false,
                        "write": false,
                        "open": true,
                        "name": "project",
                        "sub_name": "Internal deviation",
                        "type": null,
                        "active": "1",
                        "parent": "15849",
                        "show": "0",
                        "create": "0",
                        "children": [],
                        "update": false,
                        "visible": true
                    }
                ],
                "update": false,
                "visible": true
            },
            {
                "id": "15858",
                "checked": false,
                "eligibility": "Permit",
                "read": false,
                "write": false,
                "open": true,
                "name": "project",
                "sub_name": "Permit",
                "type": null,
                "active": "1",
                "parent": "15801",
                "show": "0",
                "create": "0",
                "children": [],
                "update": false,
                "visible": true
            },
            {
                "id": "15861",
                "checked": false,
                "eligibility": "Plan",
                "read": false,
                "write": false,
                "open": true,
                "name": "project",
                "sub_name": "Plan",
                "type": null,
                "active": "1",
                "parent": "15801",
                "show": "0",
                "create": "0",
                "children": [],
                "update": false,
                "visible": true
            },
            {
                "id": "15864",
                "checked": false,
                "eligibility": "Quality control",
                "read": false,
                "write": false,
                "open": true,
                "name": "project",
                "sub_name": "Quality control",
                "type": null,
                "active": "1",
                "parent": "15801",
                "show": "0",
                "create": "0",
                "children": [],
                "update": false,
                "visible": true
            },
            {
                "id": "15867",
                "checked": false,
                "eligibility": "Weekly Report",
                "read": false,
                "write": false,
                "open": true,
                "name": "project",
                "sub_name": "Weekly Report",
                "type": null,
                "active": "1",
                "parent": "15801",
                "show": "0",
                "create": "0",
                "children": [],
                "update": false,
                "visible": true
            },
            {
                "id": "15870",
                "checked": false,
                "eligibility": "Supplier Invoices",
                "read": false,
                "write": false,
                "open": true,
                "name": "project",
                "sub_name": "Supplier Invoices",
                "type": null,
                "active": "1",
                "parent": "15801",
                "show": "0",
                "create": "0",
                "children": [],
                "update": false,
                "visible": true
            }
        ],
        "update": false,
        "visible": true
    },
    {
        "id": "15873",
        "checked": true,
        "eligibility": "timesheets",
        "read": true,
        "write": true,
        "open": true,
        "name": "timesheets",
        "sub_name": "Global",
        "type": null,
        "active": "1",
        "parent": "0",
        "show": "1",
        "create": "1",
        "children": [
            {
                "id": "15876",
                "checked": false,
                "eligibility": "time_report_management",
                "read": false,
                "write": false,
                "open": true,
                "name": "timesheets",
                "sub_name": "time_report_management",
                "type": null,
                "active": "1",
                "parent": "15873",
                "show": "0",
                "create": "0",
                "children": [],
                "update": false,
                "visible": true
            },
            {
                "id": "15882",
                "checked": true,
                "eligibility": "payroll",
                "read": true,
                "write": true,
                "open": true,
                "name": "timesheets",
                "sub_name": "payroll",
                "type": null,
                "active": "1",
                "parent": "15873",
                "show": "1",
                "create": "1",
                "children": [],
                "update": false,
                "visible": true
            },
            {
                "id": "15879",
                "checked": true,
                "eligibility": "record time",
                "read": true,
                "write": true,
                "open": true,
                "name": "timesheets",
                "sub_name": "record time",
                "type": null,
                "active": "1",
                "parent": "15873",
                "show": "1",
                "create": "1",
                "children": [],
                "update": false,
                "visible": true
            }
        ],
        "update": false,
        "visible": true
    },
    {
        "id": "15885",
        "checked": false,
        "eligibility": "Overview",
        "read": false,
        "write": false,
        "open": true,
        "name": "project",
        "sub_name": "Overview",
        "type": null,
        "active": "1",
        "parent": "0",
        "show": "0",
        "create": "0",
        "children": [
            {
                "id": "15888",
                "checked": false,
                "eligibility": "analyzing",
                "read": false,
                "write": false,
                "open": true,
                "name": "project",
                "sub_name": "analyzing",
                "type": null,
                "active": "1",
                "parent": "15885",
                "show": "0",
                "create": "0",
                "children": [],
                "update": false,
                "visible": true
            }
        ],
        "update": false,
        "visible": true
    },
    {
        "id": "15891",
        "checked": true,
        "eligibility": "invoices",
        "read": true,
        "write": false,
        "open": true,
        "name": "invoices",
        "sub_name": "Global",
        "type": null,
        "active": "1",
        "parent": "0",
        "show": "1",
        "create": "0",
        "children": [],
        "update": false,
        "visible": true
    },
    {
        "id": "15894",
        "checked": false,
        "eligibility": "register",
        "read": false,
        "write": false,
        "open": true,
        "name": "register",
        "sub_name": "Global",
        "type": null,
        "active": "1",
        "parent": "0",
        "show": "0",
        "create": "0",
        "children": [
            {
                "id": "15897",
                "checked": false,
                "eligibility": "customers",
                "read": false,
                "write": false,
                "open": true,
                "name": "register",
                "sub_name": "customers",
                "type": null,
                "active": "1",
                "parent": "15894",
                "show": "0",
                "create": "0",
                "children": [],
                "update": false,
                "visible": true
            },
            {
                "id": "15900",
                "checked": false,
                "eligibility": "suppliers",
                "read": false,
                "write": false,
                "open": true,
                "name": "register",
                "sub_name": "suppliers",
                "type": null,
                "active": "1",
                "parent": "15894",
                "show": "0",
                "create": "0",
                "children": [],
                "update": false,
                "visible": true
            },
            {
                "id": "15903",
                "checked": false,
                "eligibility": "products",
                "read": false,
                "write": false,
                "open": true,
                "name": "register",
                "sub_name": "products",
                "type": null,
                "active": "1",
                "parent": "15894",
                "show": "0",
                "create": "0",
                "children": [],
                "update": false,
                "visible": true
            }
        ],
        "update": false,
        "visible": true
    },
    {
        "id": "15906",
        "checked": false,
        "eligibility": "users",
        "read": false,
        "write": false,
        "open": true,
        "name": "users",
        "sub_name": "Global",
        "type": null,
        "active": "1",
        "parent": "0",
        "show": "0",
        "create": "0",
        "children": [
            {
                "id": "15909",
                "checked": false,
                "eligibility": "Contact details",
                "read": false,
                "write": false,
                "open": true,
                "name": "users",
                "sub_name": "Contact details",
                "type": null,
                "active": "1",
                "parent": "15906",
                "show": "0",
                "create": "0",
                "children": [],
                "update": false,
                "visible": true
            },
            {
                "id": "15912",
                "checked": false,
                "eligibility": "Manage users",
                "read": false,
                "write": false,
                "open": true,
                "name": "users",
                "sub_name": "Manage users",
                "type": null,
                "active": "1",
                "parent": "15906",
                "show": "0",
                "create": "0",
                "children": [],
                "update": false,
                "visible": true
            }
        ],
        "update": false,
        "visible": true
    },
    {
        "id": "15915",
        "checked": true,
        "eligibility": "notice",
        "read": true,
        "write": true,
        "open": true,
        "name": "notice",
        "sub_name": "Global",
        "type": null,
        "active": "1",
        "parent": "0",
        "show": "1",
        "create": "1",
        "children": [
            {
                "id": "15918",
                "checked": true,
                "eligibility": "time_registration",
                "read": true,
                "write": true,
                "open": true,
                "name": "notice",
                "sub_name": "time_registration",
                "type": null,
                "active": "1",
                "parent": "15915",
                "show": "1",
                "create": "1",
                "children": [],
                "update": false,
                "visible": true
            },
            {
                "id": "15921",
                "checked": false,
                "eligibility": "ata_and_KS",
                "read": false,
                "write": false,
                "open": true,
                "name": "notice",
                "sub_name": "ata_and_KS",
                "type": null,
                "active": "1",
                "parent": "15915",
                "show": "0",
                "create": "0",
                "children": [],
                "update": false,
                "visible": true
            },
            {
                "id": "15924",
                "checked": false,
                "eligibility": "deviation",
                "read": false,
                "write": false,
                "open": true,
                "name": "notice",
                "sub_name": "deviation",
                "type": null,
                "active": "1",
                "parent": "15915",
                "show": "0",
                "create": "0",
                "children": [],
                "update": false,
                "visible": true
            },
            {
                "id": "15927",
                "checked": false,
                "eligibility": "weekly_report",
                "read": false,
                "write": false,
                "open": true,
                "name": "notice",
                "sub_name": "weekly_report",
                "type": null,
                "active": "1",
                "parent": "15915",
                "show": "0",
                "create": "0",
                "children": [],
                "update": false,
                "visible": true
            },
            {
                "id": "15930",
                "checked": false,
                "eligibility": "order",
                "read": false,
                "write": false,
                "open": true,
                "name": "notice",
                "sub_name": "order",
                "type": null,
                "active": "1",
                "parent": "15915",
                "show": "0",
                "create": "0",
                "children": [],
                "update": false,
                "visible": true
            }
        ],
        "update": false,
        "visible": true
    },
    {
        "id": "15933",
        "checked": true,
        "eligibility": "help",
        "read": true,
        "write": true,
        "open": true,
        "name": "help",
        "sub_name": "Global",
        "type": null,
        "active": "1",
        "parent": "0",
        "show": "1",
        "create": "1",
        "children": [],
        "update": false,
        "visible": true
    },
    {
        "id": "15936",
        "checked": false,
        "eligibility": "settings",
        "read": false,
        "write": false,
        "open": true,
        "name": "settings",
        "sub_name": "Global",
        "type": null,
        "active": "1",
        "parent": "0",
        "show": "0",
        "create": "0",
        "children": [],
        "update": false,
        "visible": true
    },
    {
        "id": "15939",
        "checked": true,
        "eligibility": "feedback",
        "read": true,
        "write": true,
        "open": true,
        "name": "feedback",
        "sub_name": "Global",
        "type": null,
        "active": "1",
        "parent": "0",
        "show": "1",
        "create": "1",
        "children": [],
        "update": false,
        "visible": true
    }
];