export const defaultStyle = {
  userColumnGrid: "21px 185px 118px",
  userWrapperWidth: 324,
  rowHeight: 36,
  rowHeightHalf: 36 / 2,
  headerHeight: 36,
  calendarColumnWidth: 43,
  calendarColumnWidthHalf: 43 / 2,
  fontSizeXS: "6px",
  fontSizeSmall: "8px",
  fontSizeMedium: "10px",
  fontSizeLarge: "12px",
  defaultFontSize: 12,
  dayFieldColumnPadding: 1,
  userPaddingTopGrid: 13,
  userPaddingTopGridHalf: 6.5,
  circleHeight: 33,
  circleWidth: 33,
  circleTextTop: 34,
  multipleAbsencesWidth: 54,
  multipleAbsencesHeight: 38,
  modalHeight: 557.81,
  opacity: 0,
  nrOfWeeks: 31,
};
